using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UserMaker.Class
{
	internal class TicketInfo
	{
		// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
		// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);

		//All the classes from the api request result 
		public class AccessControl
		{
			public int id { get; set; }
			public string entity { get; set; }
			public int entity_id { get; set; }
			public int type { get; set; }
			public int agent_id { get; set; }
			public int user_id { get; set; }
			public int role_id { get; set; }
			public int team_id { get; set; }
			public int department_id { get; set; }
			public int level { get; set; }
			public string entity_text_id { get; set; }
		}

		public class Client
		{
			public int id { get; set; }
			public string name { get; set; }
			public int toplevel_id { get; set; }
			public string toplevel_name { get; set; }
			public bool inactive { get; set; }
			public string colour { get; set; }
			public int confirmemail { get; set; }
			public int actionemail { get; set; }
			public int clearemail { get; set; }
			public int messagegroup_id { get; set; }
			public bool override_org_logo { get; set; }
			public string override_org_name { get; set; }
			public string override_org_phone { get; set; }
			public string override_org_email { get; set; }
			public string override_org_website { get; set; }
			public string override_org_portalurl { get; set; }
			public int mailbox_override { get; set; }
			public int default_mailbox_id { get; set; }
			public int item_tax_code { get; set; }
			public int service_tax_code { get; set; }
			public int prepay_tax_code { get; set; }
			public int contract_tax_code { get; set; }
			public string thirdpartynhdapiurl { get; set; }
			public string xeroid { get; set; }
			public int main_site_id { get; set; }
			public string main_site_name { get; set; }
			public bool override_portalcolour { get; set; }
			public bool isnhserveremaildefault { get; set; }
			public string use { get; set; }
			public string xero_tenant_id { get; set; }
			public int overridepdftemplateinvoice { get; set; }
			public int kashflow_tenant_id { get; set; }
			public int client_to_invoice { get; set; }
			public string client_to_invoice_name { get; set; }
			public int invoiceduedaysextraclient { get; set; }
			public string itglue_id { get; set; }
			public string clientcurrency { get; set; }
			public string sentinel_subscription_id { get; set; }
			public string sentinel_workspace_name { get; set; }
			public string sentinel_resource_group_name { get; set; }
			public int sentinel_tenant_id { get; set; }
			public int default_currency_code { get; set; }
			public int client_to_invoice_recurring { get; set; }
			public string client_to_invoice_recurring_name { get; set; }
			public int cautomateid { get; set; }
			public string dbc_company_id { get; set; }
			public List<object> customer_relationship { get; set; }
			public int sentinel_default_user_override { get; set; }
			public bool ticket_invoices_for_each_site { get; set; }
			public bool is_vip { get; set; }
			public bool taxable { get; set; }
			public int percentage_to_survey { get; set; }
			public int overridepdftemplatequote { get; set; }
		}

		public class Customfield
		{
			public int id { get; set; }
			public string name { get; set; }
			public string label { get; set; }
			public string summary { get; set; }
			public int type { get; set; }
			public object value { get; set; }
			public string display { get; set; }
			public int characterlimit { get; set; }
			public int characterlimittype { get; set; }
			public int inputtype { get; set; }
			public bool copytochild { get; set; }
			public bool searchable { get; set; }
			public bool ordervalues { get; set; }
			public int ordervaluesby { get; set; }
			public bool database_lookup_auto { get; set; }
			public int extratype { get; set; }
			public bool copytochildonupdate { get; set; }
			public int usage { get; set; }
			public bool showondetailsscreen { get; set; }
			public string third_party_value { get; set; }
			public int custom_extra_table_id { get; set; }
			public bool copytorelated { get; set; }
			public string calculation { get; set; }
			public int rounding { get; set; }
			public string regex { get; set; }
			public bool is_horizontal { get; set; }
			public bool isencrypted { get; set; }
			public int selection_field_id { get; set; }
			public bool showintable { get; set; }
			public int load_type { get; set; }
			public string third_party_name { get; set; }
			public string hyperlink { get; set; }
			public int? linked_table_id { get; set; }
			public bool? new_storage_method { get; set; }
			public int? table_data_entry_type { get; set; }
		}

		public class DefaultService
		{
			public int id { get; set; }
			public string guid { get; set; }
			public string name { get; set; }
			public string summary { get; set; }
			public int sequence { get; set; }
			public bool showinusercatalog { get; set; }
			public bool showintechcatalog { get; set; }
			public bool trackstatus { get; set; }
			public int service_category_id { get; set; }
			public string service_category_name { get; set; }
			public int business_owner_id { get; set; }
			public int business_owner_cab_id { get; set; }
			public int technical_owner_id { get; set; }
			public int technical_owner_cab_id { get; set; }
			public int compliance_owner_id { get; set; }
			public int compliance_owner_cab_id { get; set; }
			public double cost { get; set; }
			public int estimated_delivery { get; set; }
			public int estimated_delivery_days { get; set; }
			public bool subscribable { get; set; }
			public int subscriber_count { get; set; }
			public int asset_count { get; set; }
			public int assettype_id { get; set; }
			public string assettype_ids { get; set; }
			public bool using_default_public_message { get; set; }
			public int service_tickettype_id { get; set; }
			public bool serviceshownewreqscreen { get; set; }
			public int service_template_id { get; set; }
			public int newservicereqtype { get; set; }
			public int incident_tickettype_id { get; set; }
			public int incident_template_id { get; set; }
			public int newincidenttype { get; set; }
			public int relatedworkdayid { get; set; }
			public int requestdetails_count { get; set; }
			public string requestdetail_url { get; set; }
			public bool requestdetail_shownewreqscreen { get; set; }
			public int requestdetail_type { get; set; }
			public int screenafterlogging { get; set; }
			public double pricingrange { get; set; }
			public int override_site_id { get; set; }
			public bool failcreaterequest { get; set; }
			public int workdays { get; set; }
			public int checkminutes { get; set; }
			public bool failalwaysnewrequest { get; set; }
			public int criticality { get; set; }
			public string use { get; set; }
			public string icon { get; set; }
			public string service_url { get; set; }
			public string incident_url { get; set; }
		}

		public class Field
		{
			public int id { get; set; }
			public string name { get; set; }
			public string validate { get; set; }
			public bool mandatory { get; set; }
			public bool showonactivity { get; set; }
			public int lookup { get; set; }
			public int systemuse { get; set; }
			public int parenttype_id { get; set; }
			public string url { get; set; }
			public int access_level { get; set; }
			public bool copytochildonupdate { get; set; }
			public int rtid { get; set; }
			public int fieldid { get; set; }
			public int seq { get; set; }
			public int tableid { get; set; }
			public int groupid { get; set; }
			public int endusernew { get; set; }
			public int enduserdetail { get; set; }
			public int technew { get; set; }
			public int techdetail { get; set; }
			public Fieldinfo fieldinfo { get; set; }
			public List<object> visibility_conditions { get; set; }
			public List<object> visibility_conditions_value { get; set; }
			public List<object> value_restrictions { get; set; }
			public int technewlocation { get; set; }
			public int restrictupdate { get; set; }
			public List<UpdateRestriction> update_restrictions { get; set; }
			public int techtab_id { get; set; }
			public string techtab_name { get; set; }
			public bool canupdate { get; set; }
			public string override_fieldname { get; set; }
			public bool boldlabelandvalue { get; set; }
			public bool copytochild { get; set; }
			public bool copytorelated { get; set; }
			public int restrictread { get; set; }
			public int techaction { get; set; }
			public int enduseraction { get; set; }
			public bool endusercheckboxmandatory { get; set; }
			public int display_type { get; set; }
			public Group group { get; set; }
			public bool? enduserdetailhideifempty { get; set; }
			public bool? techdetailhideifempty { get; set; }
			public string guid { get; set; }
			public string label { get; set; }
			public string labellong { get; set; }
			public string summary { get; set; }
			public string hint { get; set; }
			public int type { get; set; }
			public int custom { get; set; }
			public int usage { get; set; }
			public int tab_id { get; set; }
			public string tab_name { get; set; }
			public int tab_sequence { get; set; }
			public int tab_columns { get; set; }
			public bool addunknown { get; set; }
			public int extratype { get; set; }
			public int characterlimit { get; set; }
			public int characterlimittype { get; set; }
			public int inputtype { get; set; }
			public bool searchable { get; set; }
			public bool user_searchable { get; set; }
			public bool calendar_searchable { get; set; }
			public bool ordervaluesalphanumerically { get; set; }
			public int ordervalueby { get; set; }
			public List<Value> values { get; set; }
			public string variable_name { get; set; }
			public bool database_lookup_auto { get; set; }
			public bool showintable { get; set; }
			public int visibility { get; set; }
			public bool showhintondetails { get; set; }
			public bool showondetailsscreen { get; set; }
			public int selection_field_id { get; set; }
			public int customextratableid { get; set; }
			public bool deleteafterclosure { get; set; }
			public int deleteafterclosuredays { get; set; }
			public int defaultdate { get; set; }
			public string calculation { get; set; }
			public int rounding { get; set; }
			public string regex { get; set; }
			public bool excludefromallfields { get; set; }
			public bool inherit_ac_from_tickettype { get; set; }
			public bool is_horizontal { get; set; }
			public bool showoncrmnote { get; set; }
			public bool isencrypted { get; set; }
			public int sql_connection_type { get; set; }
			public int hint_type { get; set; }
			public int load_type { get; set; }
		}

		public class Fieldinfo
		{
			public int id { get; set; }
			public string guid { get; set; }
			public string name { get; set; }
			public string label { get; set; }
			public string labellong { get; set; }
			public string summary { get; set; }
			public string hint { get; set; }
			public int lookup { get; set; }
			public int type { get; set; }
			public int custom { get; set; }
			public int usage { get; set; }
			public int tab_id { get; set; }
			public string tab_name { get; set; }
			public int tab_sequence { get; set; }
			public int tab_columns { get; set; }
			public bool addunknown { get; set; }
			public int extratype { get; set; }
			public int characterlimit { get; set; }
			public int characterlimittype { get; set; }
			public int inputtype { get; set; }
			public bool copytochild { get; set; }
			public bool searchable { get; set; }
			public bool user_searchable { get; set; }
			public bool calendar_searchable { get; set; }
			public string defaultvalue { get; set; }
			public bool ordervaluesalphanumerically { get; set; }
			public int ordervalueby { get; set; }
			public string variable_name { get; set; }
			public bool database_lookup_auto { get; set; }
			public bool copytochildonupdate { get; set; }
			public bool showintable { get; set; }
			public bool showhintondetails { get; set; }
			public bool showondetailsscreen { get; set; }
			public int selection_field_id { get; set; }
			public int customextratableid { get; set; }
			public bool copytorelated { get; set; }
			public bool deleteafterclosure { get; set; }
			public int deleteafterclosuredays { get; set; }
			public int defaultdate { get; set; }
			public List<object> validation_data { get; set; }
			public string calculation { get; set; }
			public int rounding { get; set; }
			public string regex { get; set; }
			public bool excludefromallfields { get; set; }
			public bool mandatory { get; set; }
			public bool inherit_ac_from_tickettype { get; set; }
			public bool is_horizontal { get; set; }
			public bool isencrypted { get; set; }
			public int sql_connection_type { get; set; }
			public int sql_certificate_id { get; set; }
			public int hint_type { get; set; }
			public bool new_storage_method { get; set; }
			public int load_type { get; set; }
			public bool showoncrmnote { get; set; }
			public List<Value> values { get; set; }
			public int? table_id { get; set; }
			public bool? @readonly { get; set; }
			public string calcfield { get; set; }
			public string third_party_name { get; set; }
			public string sqllookup { get; set; }
			public string importalias { get; set; }
			public string hyperlink { get; set; }
			public string groupname { get; set; }
			public TableInfo table_info { get; set; }
			public int? table_data_entry_type { get; set; }
		}

		public class Group
		{
			public int id { get; set; }
			public string header { get; set; }
			public List<Field> fields { get; set; }
			public List<object> visibility_conditions { get; set; }
		}

		public class Priority
		{
			public string id { get; set; }
			public int slaid { get; set; }
			public int priorityid { get; set; }
			public string name { get; set; }
			public double fixtime { get; set; }
			public string fixunits { get; set; }
			public bool enterslaexcuse { get; set; }
			public double responsetime { get; set; }
			public string responseunits { get; set; }
			public bool ishidden { get; set; }
			public bool fixendofday { get; set; }
			public bool responseendofday { get; set; }
			public string colour { get; set; }
			public int workdaysoverride { get; set; }
			public bool responsestartofday { get; set; }
			public string responsestartofdaytime { get; set; }
			public bool startofday { get; set; }
			public string startofdaytime { get; set; }
			public bool setfixtostartdate { get; set; }
			public bool setfixtotargetdate { get; set; }
		}

		public class Root
		{
			public int id { get; set; }
			public DateTime dateoccurred { get; set; }
			public string summary { get; set; }
			public string details { get; set; }
			public int status_id { get; set; }
			public int tickettype_id { get; set; }
			public int sla_id { get; set; }
			public string sla_name { get; set; }
			public int priority_id { get; set; }
			public Priority priority { get; set; }
			public int client_id { get; set; }
			public string client_name { get; set; }
			public int site_id { get; set; }
			public string site_name { get; set; }
			public int user_id { get; set; }
			public string user_name { get; set; }
			public string team { get; set; }
			public int agent_id { get; set; }
			public string category_1 { get; set; }
			public string category_2 { get; set; }
			public string category_3 { get; set; }
			public string category_4 { get; set; }
			public double estimate { get; set; }
			public double estimatedays { get; set; }
			public double timetaken { get; set; }
			public string supplier_name { get; set; }
			public int child_count { get; set; }
			public int attachment_count { get; set; }
			public bool flagged { get; set; }
			public bool read { get; set; }
			public int enduserstatus { get; set; }
			public bool onhold { get; set; }
			public DateTime respondbydate { get; set; }
			public DateTime fixbydate { get; set; }
			public bool excludefromsla { get; set; }
			public double slaholdtime { get; set; }
			public string site_timezone { get; set; }
			public DateTime slaactiondate { get; set; }
			public double slapercused { get; set; }
			public double slatimeleft { get; set; }
			public double currentelapsedhours { get; set; }
			public DateTime lastactiondate { get; set; }
			public DateTime last_update { get; set; }
			public int organisation_id { get; set; }
			public int department_id { get; set; }
			public string reportedby { get; set; }
			public string user_email { get; set; }
			public string emailtolist { get; set; }
			public int matched_kb_id { get; set; }
			public int product_id { get; set; }
			public int release_id { get; set; }
			public int release2_id { get; set; }
			public int release3_id { get; set; }
			public DateTime lastincomingemail { get; set; }
			public int workflow_id { get; set; }
			public int workflow_step { get; set; }
			public int workflow_seq { get; set; }
			public int pipeline_stage_id { get; set; }
			public bool is_vip { get; set; }
			public bool isimportantcontact { get; set; }
			public bool inactive { get; set; }
			public int impact { get; set; }
			public int urgency { get; set; }
			public string starttime { get; set; }
			public int starttimeslot { get; set; }
			public DateTime targetdate { get; set; }
			public string targettime { get; set; }
			public int targettimeslot { get; set; }
			public DateTime deadlinedate { get; set; }
			public string oppcontactname { get; set; }
			public string oppcompanyname { get; set; }
			public string oppemailaddress { get; set; }
			public string opptel { get; set; }
			public string oppcountry { get; set; }
			public string oppregion { get; set; }
			public string opptype { get; set; }
			public double oppvalueadjusted { get; set; }
			public string opptimezonename { get; set; }
			public double cost { get; set; }
			public int quantity { get; set; }
			public string userdef1 { get; set; }
			public string userdef2 { get; set; }
			public string userdef3 { get; set; }
			public string userdef4 { get; set; }
			public string userdef5 { get; set; }
			public int source { get; set; }
			public bool release_important { get; set; }
			public int releasenotegroup_id { get; set; }
			public int supplier_status { get; set; }
			public int appointment_type { get; set; }
			public List<Customfield> customfields { get; set; }
			public string section_timezone { get; set; }
			public bool projectinternaltask { get; set; }
			public int impactlevel { get; set; }
			public string guid { get; set; }
			public string phonenumber { get; set; }
			public string details_html { get; set; }
			public string takenby { get; set; }
			public DateTime datecreated { get; set; }
			public int createdfrom_id { get; set; }
			public int top_level_id { get; set; }
			public int site_sla_id { get; set; }
			public int supplier_contract_id { get; set; }
			public bool supplier_breachrespsent { get; set; }
			public bool supplier_breachfixbysent { get; set; }
			public bool showforusers { get; set; }
			public string messsent { get; set; }
			public bool agreedcleared { get; set; }
			public int risklevel { get; set; }
			public int service_id { get; set; }
			public bool surveysent { get; set; }
			public string approval_process_step_name { get; set; }
			public bool inform3rdpartysystem { get; set; }
			public bool surveyneeded { get; set; }
			public bool knownerror { get; set; }
			public bool development { get; set; }
			public int changeseq { get; set; }
			public int mailboxid { get; set; }
			public bool actisbillabledefault { get; set; }
			public int chargerate { get; set; }
			public string timezonename { get; set; }
			public bool forwardinboundupdates { get; set; }
			public bool loggedoutofhdworkinghours { get; set; }
			public bool acctmaninformedsurvey { get; set; }
			public int laststatuschangeinformed { get; set; }
			public int auditstatus { get; set; }
			public int auditunum { get; set; }
			public DateTime auditdate { get; set; }
			public bool oppdontaddtomailinglist { get; set; }
			public int sendprintrequest { get; set; }
			public string pagerdutyid { get; set; }
			public string pagerdutyincidentidstring { get; set; }
			public int pagerdutystatus { get; set; }
			public string product_name { get; set; }
			public int component_id { get; set; }
			public int version_id { get; set; }
			public string mailentryid { get; set; }
			public int contract_id { get; set; }
			public string workflow_name { get; set; }
			public DateTime workflow_stepstarted { get; set; }
			public int laststatuschangeinformedmanager { get; set; }
			public int currency { get; set; }
			public int projectconsignmentheaderid { get; set; }
			public int projectconsignmentdetailid { get; set; }
			public int servicefailurestid { get; set; }
			public int hdid { get; set; }
			public bool deleted { get; set; }
			public int matched_rule_id { get; set; }
			public bool ignore_kb_match { get; set; }
			public double deadlinenotificationhours { get; set; }
			public bool showonroadmap { get; set; }
			public string phonenumberfrom { get; set; }
			public string addressfrom { get; set; }
			public int team_id { get; set; }
			public int team_department_id { get; set; }
			public User user { get; set; }
			public Tickettype tickettype { get; set; }
			public int newaction_emailfrom { get; set; }
			public string newaction_emailfrom_address_override { get; set; }
			public bool _canupdate { get; set; }
			public int appointment_count { get; set; }
			public int open_chat_count { get; set; }
			public int task_count { get; set; }
			public List<Viewer> viewers { get; set; }
			public string reference { get; set; }
			public string email_start_tag_override { get; set; }
			public string email_end_tag_override { get; set; }
			public int follower_count { get; set; }
			public int todo_count { get; set; }
			public int service_count { get; set; }
			public List<Service> services { get; set; }
			public bool is_opportunity { get; set; }
			public bool is_project { get; set; }
			public int items_issued_count { get; set; }
			public int quotation_count { get; set; }
			public int salesorder_count { get; set; }
			public int purchaseorder_count { get; set; }
			public int invoice_line_count { get; set; }
			public int budgettype_id { get; set; }
			public string azure_tenants_name { get; set; }
			public bool canbechild { get; set; }
			public bool locked { get; set; }
			public bool has_related { get; set; }
			public int pagerdutyeragent { get; set; }
			public string devops_agent { get; set; }
			public int devops_comment_count { get; set; }
			public int your_vote { get; set; }
			public string your_vote_comment { get; set; }
			public int scomalertstate { get; set; }
			public int orionalertid { get; set; }
			public int orionalertactiveid { get; set; }
			public int orionacknowledgestate { get; set; }
			public int orionclosestate { get; set; }
			public int orionacknowledgedby { get; set; }
			public DateTime orionacknowledgedate { get; set; }
			public string orionacknowledgenote { get; set; }
			public string orionalertname { get; set; }
			public string servicenow_id { get; set; }
			public string splunkoncall_id { get; set; }
			public string splunkoncallurl { get; set; }
			public int splunkoncallstatus { get; set; }
			public int connectwise_id { get; set; }
			public int connectwise_project_id { get; set; }
			public string servicenow_number { get; set; }
			public int autotask_id { get; set; }
			public string autotask_number { get; set; }
			public int atera_alert_id { get; set; }
			public int laststatuschangestatus { get; set; }
			public DateTime laststatuschangestatusdate { get; set; }
			public string meraki_device { get; set; }
			public string meraki_alert_type { get; set; }
			public int powershell_script_count { get; set; }
			public int devops_workitem_count { get; set; }
			public string ninja_alert_id { get; set; }
			public int ninja_device_id { get; set; }
			public bool isbillable { get; set; }
			public bool itemsarebillable { get; set; }
			public string who { get; set; }
			public int resourcetype_id { get; set; }
			public int resource_booking_type { get; set; }
			public bool faultapprovalfailed { get; set; }
			public int article_type { get; set; }
			public int automate_id { get; set; }
			public int device_automate_id { get; set; }
			public string auvik_id { get; set; }
			public string auvik_url { get; set; }
			public string bookingurl { get; set; }
			public int jira_issue_count { get; set; }
			public int call_log_count { get; set; }
			public int postloggedview { get; set; }
			public int freshdesk_id { get; set; }
			public List<object> external_links { get; set; }
			public int alluserscanview { get; set; }
			public bool sync_to_salesforce { get; set; }
			public int visible_child_tickets { get; set; }
			public string primary_service_name { get; set; }
			public List<object> expenses { get; set; }
			public int ncentral_details_id { get; set; }
			public int supplier_contact_id { get; set; }
			public string pagerdutyservice { get; set; }
			public int linked_halo_ticket_count { get; set; }
			public string whatsappcreatedfromid { get; set; }
			public string sms_override { get; set; }
			public int thirdpartyreviewscore { get; set; }
			public int datto_alert_state { get; set; }
			public DateTime reviewed_date { get; set; }
			public bool is_sensitive { get; set; }
			public int contract_schedule_plan_id { get; set; }
			public bool hide_feedback { get; set; }
			public int ola_count { get; set; }
			public string use { get; set; }
			public bool canbevotedfor { get; set; }
			public double ticketage { get; set; }
			public int useful_count { get; set; }
			public int notuseful_count { get; set; }
			public bool updateservicestatus { get; set; }
			public string servicestatusnote { get; set; }
			public int itil_requesttype_id { get; set; }
			public string ticket_tags { get; set; }
			public string opp_country_name { get; set; }
			public string opp_region_name { get; set; }
			public bool invoiceseperatelyoverride { get; set; }
			public string purchaseordernumber { get; set; }
			public bool reviewed { get; set; }
			public int merged_into_id { get; set; }
		}

		public class Service
		{
			public int id { get; set; }
			public string guid { get; set; }
			public string name { get; set; }
			public string summary { get; set; }
			public int sequence { get; set; }
			public bool showinusercatalog { get; set; }
			public bool showintechcatalog { get; set; }
			public bool trackstatus { get; set; }
			public int service_category_id { get; set; }
			public string service_category_name { get; set; }
			public int business_owner_id { get; set; }
			public int business_owner_cab_id { get; set; }
			public int technical_owner_id { get; set; }
			public int technical_owner_cab_id { get; set; }
			public int compliance_owner_id { get; set; }
			public int compliance_owner_cab_id { get; set; }
			public double cost { get; set; }
			public int estimated_delivery { get; set; }
			public int estimated_delivery_days { get; set; }
			public bool subscribable { get; set; }
			public int subscriber_count { get; set; }
			public int asset_count { get; set; }
			public int assettype_id { get; set; }
			public string assettype_ids { get; set; }
			public bool using_default_public_message { get; set; }
			public int service_tickettype_id { get; set; }
			public bool serviceshownewreqscreen { get; set; }
			public int service_template_id { get; set; }
			public int newservicereqtype { get; set; }
			public int incident_tickettype_id { get; set; }
			public int incident_template_id { get; set; }
			public int newincidenttype { get; set; }
			public int relatedworkdayid { get; set; }
			public int requestdetails_count { get; set; }
			public string requestdetail_url { get; set; }
			public bool requestdetail_shownewreqscreen { get; set; }
			public int requestdetail_type { get; set; }
			public int screenafterlogging { get; set; }
			public double pricingrange { get; set; }
			public int override_site_id { get; set; }
			public bool failcreaterequest { get; set; }
			public int workdays { get; set; }
			public int checkminutes { get; set; }
			public bool failalwaysnewrequest { get; set; }
			public int criticality { get; set; }
			public string use { get; set; }
			public string icon { get; set; }
			public string service_url { get; set; }
			public string incident_url { get; set; }
		}

		public class Site
		{
			public int id { get; set; }
			public string name { get; set; }
			public double client_id { get; set; }
			public string client_name { get; set; }
			public string clientsite_name { get; set; }
			public bool inactive { get; set; }
			public int sla_id { get; set; }
			public string colour { get; set; }
			public string timezone { get; set; }
			public bool invoice_address_isdelivery { get; set; }
			public bool isstocklocation { get; set; }
			public int messagegroup_id { get; set; }
			public string maincontact_name { get; set; }
			public Client client { get; set; }
			public List<Field> fields { get; set; }
			public bool isnhserveremaildefault { get; set; }
			public int datto_alternate_id { get; set; }
			public bool all_faqlists_allowed { get; set; }
			public string use { get; set; }
			public string itglue_id { get; set; }
			public int maincontact_id { get; set; }
			public int site_item_tax_code { get; set; }
		}

		public class TableInfo
		{
			public int id { get; set; }
			public string guid { get; set; }
			public string name { get; set; }
			public string db_name { get; set; }
			public int linkto_table_id { get; set; }
			public string linkto_table_name { get; set; }
			public string note { get; set; }
			public string import_folder { get; set; }
			public int data_entry_type { get; set; }
			public bool clear_on_close { get; set; }
			public int primary_field_1 { get; set; }
			public int primary_field_2 { get; set; }
			public List<Field> fields { get; set; }
			public int customextratableid { get; set; }
			public int customtable_orderby { get; set; }
		}

		public class Tickettype
		{
			public int id { get; set; }
			public string guid { get; set; }
			public string name { get; set; }
			public string use { get; set; }
			public int sequence { get; set; }
			public int group_id { get; set; }
			public bool agentscanselect { get; set; }
			public int itilrequesttype { get; set; }
			public bool allowattachments { get; set; }
			public bool copyattachmentstochild { get; set; }
			public bool copyattachmentstorelated { get; set; }
			public bool is_sprint { get; set; }
			public bool enduserscanselect { get; set; }
			public bool anonymouscanselect { get; set; }
			public bool visible { get; set; }
			public int statusafteruserupdate { get; set; }
			public int statusaftersupplierupdate { get; set; }
			public int closedrequestswithupdates { get; set; }
			public int pendingrequestswithupdates { get; set; }
			public bool portalcanreopen { get; set; }
			public bool closedrequestswithupdatesincpending { get; set; }
			public bool includeinmobiledbsync { get; set; }
			public int workflow_id { get; set; }
			public string always_bcc { get; set; }
			public int reopenedstatus { get; set; }
			public int closedrequestsemailid { get; set; }
			public int pendingrequestsemailid { get; set; }
			public double closeduserupdatehours { get; set; }
			public double pendinguserupdatehours { get; set; }
			public int chargerate { get; set; }
			public int initial_status { get; set; }
			public bool default_team_to_agents_default { get; set; }
			public int default_sla { get; set; }
			public string default_category_1 { get; set; }
			public string default_category_2 { get; set; }
			public string default_category_3 { get; set; }
			public string default_category_4 { get; set; }
			public string default_summary { get; set; }
			public string default_details { get; set; }
			public string default_details_html { get; set; }
			public bool default_excludefromsla { get; set; }
			public bool default_showforusers { get; set; }
			public int default_sendack { get; set; }
			public bool default_sendemail { get; set; }
			public int default_matchedkbid { get; set; }
			public bool allowall_actions { get; set; }
			public bool allowall_team { get; set; }
			public bool allowall_status { get; set; }
			public bool allowall_category1 { get; set; }
			public bool allowall_category2 { get; set; }
			public bool allowall_category3 { get; set; }
			public bool allowall_category4 { get; set; }
			public int approval_process_id { get; set; }
			public int from_mailbox_id { get; set; }
			public bool hide_respond { get; set; }
			public int close_kb_action { get; set; }
			public int default_product_id { get; set; }
			public int default_budgettype_id { get; set; }
			public string email_start_tag_override { get; set; }
			public string email_end_tag_override { get; set; }
			public int acknowledgementtemplate { get; set; }
			public int acknowledgementtemplateooh { get; set; }
			public bool dontsendslareminders { get; set; }
			public bool dontusependingclosure { get; set; }
			public int database_lookup_id { get; set; }
			public bool applydefaultsontypechangebool { get; set; }
			public bool allowtickettypetobechild { get; set; }
			public List<Field> fields { get; set; }
			public double default_estimate { get; set; }
			public bool mustclosechildbeforeclosurebool { get; set; }
			public int default_sendremoteinvite { get; set; }
			public bool logtimeindays { get; set; }
			public double logtimeindaysincrement { get; set; }
			public bool usetimeslotsforstartandtargettimes { get; set; }
			public int childticketcolumnsoverride { get; set; }
			public bool showunborntab { get; set; }
			public bool allowcustomiseunborn { get; set; }
			public bool inform_account_manager { get; set; }
			public int statusaftertechupdate { get; set; }
			public int pdftemplate_id { get; set; }
			public int quote_pdftemplate_id { get; set; }
			public int maximumRestrictedPriority { get; set; }
			public int auto_respond_logged_manually { get; set; }
			public int autoCloseHours { get; set; }
			public int closedrequestreplylimit { get; set; }
			public int pendingrequestreplylimit { get; set; }
			public int alluserscanview { get; set; }
			public bool thisentitycanbevotedfor { get; set; }
			public bool show_vote_comment { get; set; }
			public int overridewiththefollowingtemplatewhenloggingmanually { get; set; }
			public bool editservstatus { get; set; }
			public int appointmentdefaultbody { get; set; }
			public bool setrelatedservicesfromassets { get; set; }
			public int default_sendtosoc { get; set; }
			public int default_soctargettype { get; set; }
			public string default_soctargetid { get; set; }
			public string default_soctargetname { get; set; }
			public bool forwardinboundupdates { get; set; }
			public string default_appointment_summary { get; set; }
			public string default_appointment_details { get; set; }
			public bool displayonquicktime { get; set; }
			public int statusafterapproverupdate { get; set; }
			public bool display_audit_tab { get; set; }
			public List<DefaultService> default_services { get; set; }
			public List<AccessControl> access_control { get; set; }
			public int access_control_level { get; set; }
			public bool showdownvote { get; set; }
			public int addactionstolinked { get; set; }
			public bool addnoteonlytolinked { get; set; }
			public bool dontconfirm_updateparent { get; set; }
			public bool isbillable { get; set; }
			public bool items_are_billable { get; set; }
			public int defaultresourcetype { get; set; }
			public int defaultlisttype { get; set; }
			public int defaulttab { get; set; }
			public bool defaultsync_to_sentinel { get; set; }
			public int default_targetdate { get; set; }
			public int agentresourcebookingtype { get; set; }
			public bool userbookfromportal { get; set; }
			public int defaultresourcetype_agent { get; set; }
			public int defaultagentresourcebookingduration_id { get; set; }
			public bool showopenusertickets { get; set; }
			public bool showopensitetickets { get; set; }
			public bool showopenclienttickets { get; set; }
			public bool showopendevicetickets { get; set; }
			public bool updateservicestatus { get; set; }
			public string default_servicestatusnote { get; set; }
			public int attendeesenduser { get; set; }
			public bool showbillingtab { get; set; }
			public bool showsuggestionstab { get; set; }
			public bool showoppcontacttab { get; set; }
			public bool showactivestatuskanban { get; set; }
			public int ganttgrandchildview { get; set; }
			public string submitlabeloverride { get; set; }
			public bool allowall_appointment_types { get; set; }
			public bool include_appointments_scheduled_hours { get; set; }
			public int ticketlinktype { get; set; }
			public bool allowall_iframe_customtabs { get; set; }
			public bool default_sync_to_salesforce { get; set; }
			public int salesforce_default_stage { get; set; }
			public bool show_add_note { get; set; }
			public int auto_delete_data { get; set; }
			public int auto_delete_days { get; set; }
			public int show_child_tasks_type { get; set; }
			public bool pin_important_actions { get; set; }
			public int parentstatusafterallchildclosed { get; set; }
			public int allowlogonbehalfof { get; set; }
			public int auto_create_appt { get; set; }
			public bool hide_anon_contact_info { get; set; }
			public string ticket_created_override { get; set; }
			public bool allow_anonymous_logging { get; set; }
			public string published_id { get; set; }
			public bool add_ack_attachments { get; set; }
			public string defaultpagerdutyservice { get; set; }
			public bool defaultsidebarcollapsed { get; set; }
			public int tab_display { get; set; }
			public int sprint_tickettype_id { get; set; }
			public bool usemilestones { get; set; }
			public int minattachments { get; set; }
			public bool make_cc_followers { get; set; }
			public int default_kanban_view { get; set; }
			public bool showgeneralsurveyfields { get; set; }
			public bool default_send_to_pagerduty { get; set; }
			public int completion_status_type { get; set; }
			public bool show_project_task_dates { get; set; }
			public int project_type { get; set; }
			public int auto_forward_email_updates { get; set; }
			public bool default_is_sensitive { get; set; }
			public int process_open_tickets { get; set; }
			public int todolistportalvisibility { get; set; }
			public bool legacy_print_request_details { get; set; }
			public bool legacy_print_service_form { get; set; }
			public int default_appt_type { get; set; }
			public bool show_child_assets { get; set; }
			public bool hide_anon_phonenumber { get; set; }
			public bool showconfirmemail { get; set; }
			public int ticket_status_after_appointment { get; set; }
			public bool milestone_billing { get; set; }
			public bool showopensuppliertickets { get; set; }
			public bool allowall_suggestion_faqlists { get; set; }
			public int startdate_validation { get; set; }
			public int targetdate_validation { get; set; }
			public bool auto_contributor { get; set; }
			public bool allow_teams_chat_creation { get; set; }
			public string teams_chat_default_name { get; set; }
			public bool show_teams_chats_as_tabs { get; set; }
			public int default_servicenow_type { get; set; }
			public bool enable_task_dependencies { get; set; }
			public bool exclude_from_sales_mailbox_match { get; set; }
			public bool show_status_on_portal { get; set; }
			public bool allow_slack_channel_creation { get; set; }
			public string slack_channel_default_name { get; set; }
			public bool show_slack_channels_as_tabs { get; set; }
			public int slack_channel_access_type { get; set; }
			public int slack_channel_workspace { get; set; }
			public int hide_anon_email { get; set; }
			public bool continue_autorelease { get; set; }
			public bool do_ai_survey { get; set; }
			public List<object> kanbanstatuschoice { get; set; }
			public string kanbanstatuschoice_list { get; set; }
			public int default_agent { get; set; }
			public string default_team { get; set; }
			public int default_priority { get; set; }
		}

		public class UpdateRestriction
		{
			public int id { get; set; }
			public int tickettype_id { get; set; }
			public int field_id { get; set; }
			public int type { get; set; }
			public int role_id { get; set; }
			public string role_name { get; set; }
			public bool alloweditbeforeapproval { get; set; }
			public bool alloweditafterapproval { get; set; }
			public bool alloweditduringapproval { get; set; }
		}

		public class User
		{
			public int id { get; set; }
			public string name { get; set; }
			public double site_id { get; set; }
			public int site_id_int { get; set; }
			public string client_name { get; set; }
			public string firstname { get; set; }
			public string surname { get; set; }
			public string initials { get; set; }
			public string emailaddress { get; set; }
			public string phonenumber_preferred { get; set; }
			public string sitephonenumber { get; set; }
			public string phonenumber { get; set; }
			public int telpref { get; set; }
			public string activedirectory_dn { get; set; }
			public string onpremise_activedirectory_dn { get; set; }
			public string login { get; set; }
			public bool inactive { get; set; }
			public string colour { get; set; }
			public bool isimportantcontact { get; set; }
			public string other1 { get; set; }
			public string other2 { get; set; }
			public string other3 { get; set; }
			public bool neversendemails { get; set; }
			public int priority_id { get; set; }
			public int linked_agent_id { get; set; }
			public bool isserviceaccount { get; set; }
			public bool isimportantcontact2 { get; set; }
			public int connectwiseid { get; set; }
			public int autotaskid { get; set; }
			public string sitetimezone { get; set; }
			public Site site { get; set; }
			public bool ismaincontact { get; set; }
			public int organisation_id { get; set; }
			public bool isnhserveremaildefault { get; set; }
			public string azure_tenant_domain { get; set; }
			public List<object> external_links { get; set; }
			public string use { get; set; }
			public int client_id { get; set; }
		}

		public class Value
		{
			public int lookupid { get; set; }
			public int id { get; set; }
			public string name { get; set; }
			public string value2 { get; set; }
			public bool value2_bool { get; set; }
			public string custom1 { get; set; }
			public string custom2 { get; set; }
		}

		public class Viewer
		{
			public int id { get; set; }
			public string name { get; set; }
			public DateTime lastlogindate { get; set; }
			public string current_action_type { get; set; }
			public string current_action_name { get; set; }
			public string use { get; set; }
		}

		public class VisibilityCondition
		{
			public int id { get; set; }
			public int tickettype_id { get; set; }
			public int field_id { get; set; }
			public int lookup_field_id { get; set; }
			public string lookup_value { get; set; }
			public int field_value { get; set; }
			public int conditiontype { get; set; }
		}



	}
}
